### PR TITLE
fix: replaced spaces with tabs

### PR DESCRIPTION
**Pull request by Cassin01**
Those spaces cause an error (I couldn't get the error out again after fixed) when I startup my neovim.

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Oh that seems very unexpected.
Could you show the error you got?

**Comment by Cassin01** [comment]
I am unable to generate the error again . Is _setup (@local c @config.lua) something that is run once without error and never run again?

**Comment by L3MON4D3** [comment]
Mhmm, that's unfortunate.. let's close this (I don't think it makes a difference), and if you encounter the error again, open an issue (or look into what's causing it and do another PR :) )

**Comment by leiserfg** [comment]
The doc itself can't cause errors. It could be that whatever you are using to generate doc tags is breaking your nvim instance :thinking:

**Comment by L3MON4D3** [comment]
As far as I understood the doc did for sure not cause this issue, spaces vs tabs in `vim.cmd` are the current suspect

**Pull request closed without merging**
