### PR TITLE
delete has_selected_text.lua + move contents to show.lua

### PR DESCRIPTION
**Pull request by JxJxxJxJ**
Added it in a new file `lua/luasnip/extras/conditions/has_selected_text.lua`. The other two files changed are just formatting.

### CODE REVIEW

**Review by JxJxxJxJ — COMMENTED** [review]
Add `has_selected_text condition`. I used `expand.lua` as template and created a new file for it

**Review by leiserfg — APPROVED** [review]

**Comment by L3MON4D3** [comment]
Thank you, first of all :+1:
I don't think it makes sense to put this into a new file, `expand` and `show` are meant to signal in which context the conditions provided by the file may be used.
With this, `has_selected_text` would fit into `show.lua`, since it can be used as a `show_condition`.

Could you make that change and squash the commits?

**Comment by L3MON4D3** [comment]
Nice so far :+1:
Could you document the new condition in `DOC.md` (there's a section explicitly for them, look for `line_end`), and squash all of the commits into just one?

**Comment by JxJxxJxJ** [comment]
I don't know how to squash the commits

**Comment by L3MON4D3** [comment]
Oh okay, I can do that too

**Comment by JxJxxJxJ** [comment]
Were the files changed accordingly?

**Comment by L3MON4D3** [comment]
Ah!
You don't have to modify `luasnip.txt` manually (actually all changes will be overwritten almost immediately), I'll just throw that commit out

**Comment by L3MON4D3** [comment]
Alright, that should do it.
If you're okay with this, I'll merge :)

**Comment by JxJxxJxJ** [comment]
Go ahead :smile:

**Comment by L3MON4D3** [comment]
Nice, thank you for the initiative :)

**Pull request merged**
