### PR TITLE
Implement semantic versioning.

### PR DESCRIPTION
**Pull request by L3MON4D3**
Hight time we do this :D

I'm thinking of doing releases regularly, using github's Release-feature for this seems to be the most straightforward way.

@leiserfg WDYT, any ideas to make this as easy as possible?

### CODE REVIEW

**Comment by leiserfg** [comment]
Maybe something like this is helpful https://github.com/semantic-release/semantic-release

**Comment by L3MON4D3** [comment]
(At least I think I'll start out with that, maybe it becomes annoying as time goes on :D)

**Comment by gegoune** [comment]
There also is https://github.com/marketplace/actions/release-please-action.

**Comment by L3MON4D3** [comment]
Oh, the release-PR seems like a nice way to keep track of changes.. I'll definitely keep that in mind :+1:

**Pull request merged**
