### PR TITLE
doc: doc.md alternate function node example

### PR DESCRIPTION
**Pull request by jrowlingson**
I don't know if I made this example more intense than it needs to be, but, writing it out this way and running it helped my understanding. The existing example does not match the gif. Double spaced to squeeze the comments in. Let me know and I'll add the gif.

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Yeah, looks good, makes sense to explain what each arg does in small comments :+1:
(+ the old one was plain incorrect with the `i(0)`, so thank you for fixing that up).
With the updated gif this is good to go :)

**Comment by jrowlingson** [comment]
Shaved the yak a bit to get this gif :laughing: (had to update ubuntu). I see that the doc generation step is adding an extra commit - shall I squash? (there's also the squash and merge option if you're using the github web client).

**Comment by L3MON4D3** [comment]
TY!!

**Comment by L3MON4D3** [comment]
(missclick :grimacing:)

**Pull request merged**
