### PR TITLE
refactor: remove deprecated function

### PR DESCRIPTION
**Pull request by huylg**
hi @L3MON4D3,

vim.pretty_print is deprecated so I have changed it to vim.print

### CODE REVIEW

**Comment by huylg** [comment]
note: tested at nvim nightly 0.10

**Comment by leiserfg** [comment]
This is deprecated since 0.9 (current stable) so it's fine to change it in the master branch.

**Comment by L3MON4D3** [comment]
Ah, thank you :+1:
Actually, right now we have compatibility down to nvim0.7 (and I don't think we need to break it for this), could you add something like [this](https://github.com/L3MON4D3/LuaSnip/blob/f3bdf8cf535b1df6f7c0122d963c6546199aa0a3/lua/luasnip/extras/snip_location.lua#L4-L9), such that 0.7 keeps working?

**Comment by L3MON4D3** [comment]
(I'll have to add a test later to catch this, they should be failing on this PR :grimacing:)

**Comment by L3MON4D3** [comment]
Superseded by #880😅

**Pull request closed without merging**
