### PR TITLE
Update luasnip.txt

### PR DESCRIPTION
**Pull request by yangxing844**
create a insertnode so that this example can work

### CODE REVIEW

**Comment by L3MON4D3** [comment]
First of all, thank you this definitely makes sense to include👍
Could you
* make the same change to `DOC.md` (the TXT is generated from it)
* and add a short comment that this insertNode is only there so the choiceNode is changeable?

**Comment by L3MON4D3** [comment]
Would you remove the first commit? Might throw off our CI otherwise

**Comment by yangxing844** [comment]
shoudl it work now? sorry this is my first pull request.

**Comment by L3MON4D3** [comment]
No worries, this is alright :) 
Thank you!

**Pull request merged**
