### PR TITLE
doc: update readme.md install instructions

### PR DESCRIPTION
**Pull request by jrowlingson**

### CODE REVIEW

**Review by gegoune — COMMENTED** [review]
Neither of code snippets will work as they are. Is it really necessary? shouldn't be plugin's responsibility to teach users how to use plugin manager they chose in the first place.

**Comment by L3MON4D3** [comment]
I agree with @gegoune, showing that one line does not make a difference.
You can add the link to packer though, it's a better recommendation than `vim-plug`

**Comment by jrowlingson** [comment]
Definitely not necessary - just a convenience I've seen [elsewhere](https://github.com/nvim-telescope/telescope.nvim#installation). Agree that anyone landing here is probably already going to be familiar with using a plugin manager.

**Comment by L3MON4D3** [comment]
This looks good, ty!
Could you squash the commits into one?

**Comment by L3MON4D3** [comment]
Nice, thank you!!

**Pull request merged**
