### PR TITLE
Add stylua auto format action

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
Sorry for the noise but I didn't have another way to check the action.

**Comment by L3MON4D3** [comment]
That's alright.
I'm not that familiar with github actions, if I were to push, say, 5 commits from my local, would the formatter run for each commit or just once?

**Comment by L3MON4D3** [comment]
Also, is a format-commit created even if the style is correct?

**Comment by leiserfg** [comment]
It is executed once per push. I didn't check if the commit happens even no change is made on a lua file, let me do it and we will see.

**Comment by leiserfg** [comment]
Looks like no, it does not crate emtpy commits.

**Comment by L3MON4D3** [comment]
Okay, that's pretty cool I'd say :+1:
TY!

**Pull request merged**
