### PR TITLE
feat: add new built-in condition for line ending

### LINKED ISSUE #592: Regular expressions with end-of-line match
Hey 👋🏾 

I'm currently trying to improve my snippets as some of them expand automatically too often when it doesn't fit. Therefore I want to check if there is nothing in the line after the trigger. In theory this should be a simple end-of-line match in the trigger. But that doesn't work. Adding this makes the snippet never expand.

Here is an example. The trigger I was using so far was ` if[%( ]`. So I simply added `$` at the end of the trigger (see below). That doesn't work. To simplify the problem I also tried ` if $`, but doesn't work neither.
Using `^` to match the start of the line works fine for me. No I'm unsure if this has something to do with how regular expressions are matched in the context of LuaSnip or if I don't understand a special case of the Lua expression syntax.

```lua
snippet(
  { trig = ' if[%( ]$', regTrig = true },
  if_node, -- ignore here to a simple example
}
```

Thanks for your help!

### PR DESCRIPTION
**Pull request by weilbith**
Closes #592

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Hey, nice :+1:
TY!

**Comment by atticus-sullivan** [comment]
Working on #612, I've looked at this code again. Is there any reason why you're just comparing the amount of characters in the string? (comparing strings in lua should be as cheap as a pointer comparison afaik)

**Comment by L3MON4D3** [comment]
Mhmm, well number of characters works because both strings are the same line, so same lengths <=> same string.
I hadn't considered that just comparing them directly could be faster, but reading up on interning, that does seem to be the case (very interesting, I would've thought looking up the result after every string-operation leads to overall worse performance, but it seems to be more nuanced that that).
I'm definitely open to making this a direct comparison, best with a comment so it's clear that this might be/is faster than comparing lengths.

**Comment by atticus-sullivan** [comment]
Alright, then I guess I'll do this change in #612 (or new PR?)

**Comment by L3MON4D3** [comment]
Amend it, different commit, same PR is alright

**Pull request merged**
