### PR TITLE
Support multi ft buffers

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
@L3MON4D3   check here first :smile:

**Comment by leiserfg** [comment]
Fixes #142

**Comment by L3MON4D3** [comment]
Nooo, I didn't see it :|

**Comment by leiserfg** [comment]
Don't worry but at least do also the loader part.

**Comment by L3MON4D3** [comment]
Actually, would you be okay with rebasing yours, just keeping `match_snippet` as is?

**Comment by leiserfg** [comment]
sure

**Comment by leiserfg** [comment]
Check now.

**Comment by L3MON4D3** [comment]
Nice :ok_hand:
ty!

**Pull request merged**
