### PR TITLE
Add stylua action to check lua style automatically

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Nice!
Does the stylua action automatically find `.lua` files in sudirectories?

**Comment by leiserfg** [comment]
Yes.

**Comment by L3MON4D3** [comment]
Great, thank you!

**Comment by leiserfg** [comment]
I think I can extendit to auto-format the code, so if someone makes an unformated pr it will get fixed without intervention.

**Comment by L3MON4D3** [comment]
That would be even better. Is it possible to have the changes as a separate commit?

**Comment by leiserfg** [comment]
Yes, I'll do that.

**Pull request merged**
