### PR TITLE
Fix otf doc for when luasnip messes with the last register somehow

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
I noticed that sometimes the second usage does not work fine as the last register gets overridden, so let's make it explicit there.

**Comment by leiserfg** [comment]
Don't merge it, I will it look even nicer :smile:

**Comment by L3MON4D3** [comment]
Nice👌👌

**Comment by L3MON4D3** [comment]
Ty!

**Pull request merged**
