### PR TITLE
Improve lazy load

### PR DESCRIPTION
**Pull request by L3MON4D3**
Title. Now we don't load essentially all of luasnip if it isn't even required :sweat_smile:

`require("luasnip")`:
Without this patch
```
004.359  000.062  000.062: require('luasnip.session')
004.666  000.305  000.305: require('luasnip.util.util')
004.719  000.052  000.052: require('luasnip.util.types')
004.897  000.084  000.084: require('luasnip.util.ext_opts')
004.899  000.178  000.095: require('luasnip.nodes.util')
004.951  000.051  000.051: require('luasnip.util.events')
004.958  000.833  000.184: require('luasnip.nodes.node')
005.161  000.065  000.065: require('luasnip.util.extend_decorator')
005.166  000.206  000.141: require('luasnip.nodes.insertNode')
005.251  000.085  000.085: require('luasnip.nodes.textNode')
005.352  000.099  000.099: require('luasnip.util.mark')
005.782  000.327  000.327: require('luasnip.util._builtin_vars')
005.847  000.062  000.062: require('vim.inspect')
005.867  000.514  000.125: require('luasnip.util.environ')
005.956  000.088  000.088: require('luasnip.util.pattern_tokenizer')
006.023  000.066  000.066: require('luasnip.util.dict')
006.178  000.154  000.154: require('luasnip.session.snippet_collection')
006.251  002.573  000.528: require('luasnip.nodes.snippet')
006.423  000.059  000.059: require('luasnip.loaders._caches')
006.530  000.106  000.106: require('luasnip.util.path')
006.540  000.287  000.122: require('luasnip.loaders')
006.655  000.112  000.112: require('luasnip.util.log')
006.801  000.137  000.137: require('luasnip.nodes.functionNode')
007.071  000.269  000.269: require('luasnip.nodes.choiceNode')
007.334  000.261  000.261: require('luasnip.nodes.dynamicNode')
007.475  000.140  000.140: require('luasnip.nodes.restoreNode')
007.841  000.094  000.094: require('luasnip.util.parser.neovim_ast')
008.302  000.083  000.083: require('luasnip.util.directed_graph')
008.307  000.736  000.560: require('luasnip.util.parser.ast_utils')
008.515  000.059  000.059: require('luasnip.util.functions')
008.519  000.211  000.152: require('luasnip.util.parser.ast_parser')
008.707  000.188  000.188: require('luasnip.util.parser.neovim_parser')
008.790  000.081  000.081: require('luasnip.util.str')
008.793  001.316  000.099: require('luasnip.util.parser')
009.923  000.107  000.107: require('vim.treesitter.language')
009.931  000.411  000.304: require('vim.treesitter.query')
010.216  000.284  000.284: require('vim.treesitter.languagetree')
010.241  000.915  000.219: require('vim.treesitter')
010.374  001.397  000.483: require('nvim-treesitter.parsers')
010.771  000.156  000.156: require('nvim-treesitter.utils')
010.777  000.401  000.245: require('nvim-treesitter.ts_utils')
010.778  001.869  000.071: require('luasnip.extras.filetype_functions')
010.846  000.057  000.057: require('luasnip.nodes.absolute_indexer')
010.972  000.125  000.125: require('luasnip.extras')
011.108  000.134  000.134: require('luasnip.extras.fmt')
011.304  000.090  000.090: require('luasnip.extras.conditions')
011.359  000.053  000.053: require('luasnip.extras.conditions.show')
011.361  000.205  000.062: require('luasnip.extras.conditions.expand')
011.362  000.253  000.048: require('luasnip.extras.expand_conditions')
011.465  000.102  000.102: require('luasnip.extras.postfix')
011.728  002.935  000.394: require('luasnip.config')
011.731  008.891  000.862: require('luasnip')
```
With this patch
```
003.259  000.049  000.049: require('luasnip.session')
003.266  000.313  000.264: require('luasnip.util.util')
003.401  000.135  000.135: require('luasnip.session.snippet_collection')
003.857  000.339  000.339: require('luasnip.util._builtin_vars')
003.878  000.019  000.019: require('vim.inspect')
003.905  000.502  000.144: require('luasnip.util.environ')
003.966  000.060  000.060: require('luasnip.util.extend_decorator')
004.089  000.045  000.045: require('luasnip.loaders._caches')
004.175  000.084  000.084: require('luasnip.util.path')
004.184  000.217  000.087: require('luasnip.loaders')
004.279  000.093  000.093: require('luasnip.util.log')
004.453  000.043  000.043: require('luasnip.util.types')
004.554  000.100  000.100: require('luasnip.util.ext_opts')
005.537  000.091  000.091: require('vim.treesitter.language')
005.544  000.368  000.277: require('vim.treesitter.query')
005.809  000.264  000.264: require('vim.treesitter.languagetree')
005.825  000.850  000.218: require('vim.treesitter')
005.948  001.332  000.482: require('nvim-treesitter.parsers')
006.256  000.116  000.116: require('nvim-treesitter.utils')
006.259  000.310  000.195: require('nvim-treesitter.ts_utils')
006.261  001.706  000.063: require('luasnip.extras.filetype_functions')
006.358  002.072  000.223: require('luasnip.config')
006.360  004.157  000.765: require('luasnip')
```
(generated via)
@clason, can you confirm success on your end? :D

### CODE REVIEW

**Comment by clason** [comment]
I'm getting an error with my config:
```
...share/nvim/lazy/luasnip/lua/luasnip/loaders/from_lua.lua:64: Failed to execute .config/nvim/luasnippets/all.lua
: [string "---@diagnostic disable: undefined-global..."]:3: attempt to call global 'p' (a nil value)
# stacktrace:
  - /luasnip/lua/luasnip/loaders/from_lua.lua:64 _in_ **load_files**
  - /luasnip/lua/luasnip/loaders/from_lua.lua:171 _in_ **lazy_load**
  - .config/nvim/lua/plugins/luasnip.lua:5 _in_ **config**
  ```
relevant config:
```lua
  require('luasnip').config.setup { update_events = 'TextChanged,TextChangedI' }
  require('luasnip.loaders.from_lua').lazy_load()
```

**Comment by L3MON4D3** [comment]
Oh, okay, let that be a lesson for me to not blindly trust the tests.
The metatable of `snip_env` was not transferred when `setfenv`-ing it on the lua-files :grimacing:
The tests didn't catch this because all the usual functions, `s`, `i`, `p`, were set-up globally such that they are quickly available for writing tests. Side-effect, of course, is that they are also available in the lua-loader-files, indendently of the `snip_env`

Could you try again?

**Comment by clason** [comment]
yep, works now! Unfortunately, I don't see much difference in loading time... (but I'm using lazy, so it's not clear how much the caching influences things)

Ok, disabling the cache shows about the same difference as in your tests 👍

**Comment by L3MON4D3** [comment]
Damn, okay that's a bit disappointing xD

I've removed the dependency on nvim-treesitter, so that might help it a bit further.
I'd say that covers the low-hanging fruits :D

**Comment by L3MON4D3** [comment]
For reference, this is what startup looks like now
```
004.455  000.061  000.061: require('luasnip.session')
004.463  000.425  000.364: require('luasnip.util.util')
004.623  000.159  000.159: require('luasnip.session.snippet_collection')
005.068  000.331  000.331: require('luasnip.util._builtin_vars')
005.093  000.022  000.022: require('vim.inspect')
005.112  000.488  000.135: require('luasnip.util.environ')
005.188  000.075  000.075: require('luasnip.util.extend_decorator')
005.335  000.053  000.053: require('luasnip.loaders._caches')
005.438  000.102  000.102: require('luasnip.util.path')
005.448  000.258  000.104: require('luasnip.loaders')
005.557  000.106  000.106: require('luasnip.util.log')
005.755  000.048  000.048: require('luasnip.util.types')
005.880  000.124  000.124: require('luasnip.util.ext_opts')
005.952  000.071  000.071: require('luasnip.extras.filetype_functions')
006.079  000.514  000.270: require('luasnip.config')
006.081  003.167  001.141: require('luasnip')
```

**Comment by clason** [comment]
> I've removed the dependency on nvim-treesitter, so that might help it a bit further.

That's a very good idea! 

> Damn, okay that's a bit disappointing xD

Maybe just lazy being _too_ clever ;)

**Comment by L3MON4D3** [comment]
> Maybe just lazy being too clever ;)

Yeah, let's chalk it up to that :D
Thank you for testing :)

**Pull request merged**
