### PR TITLE
Use nvim_get_runtime_file

### PR DESCRIPTION
**Pull request by saadparwaiz1**
Instead of searching through all runtime directories only search directories where a package.json exists. I think it might help with performance still need to run benchmarks to see if it does.

### CODE REVIEW

**Comment by L3MON4D3** [comment]
Sounds good, if performance isn't worse than without and @leiserfg gives his OK I'm happy to merge :D

**Comment by leiserfg** [comment]
Sorry for the delay, It seems good to go, I'm not sure how faster it will be (as anyway, it has to iter over the paths) but it C so, should be faster.

**Comment by leiserfg** [comment]
This will be more useful for the lazy loading as I have to store the paths, so, consider extracting that bit of code out (as a small function) so I can reuse it there.

**Comment by saadparwaiz1** [comment]
It's done!

**Comment by leiserfg** [comment]
Thanks @saadparwaiz1

**Comment by L3MON4D3** [comment]
Nice!

**Pull request merged**
