### PR TITLE
Fix loader by using the same package name as imported in the AU

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by L3MON4D3** [comment]
That would still misbehave in the (admittedly contrived, but still imaginable) scenario that both the `/`- and the `.`-version are called, wouldn't it?

**Comment by leiserfg** [comment]
I'm just avoiding cluttering the `luasnip` namespace. If you think that's the only way...

**Comment by L3MON4D3** [comment]
Yeah, that's a bit of a problem, we'll have to clean up there a bit, collect all nodes in a table or something.
Imo this doesn't really make it much worse, so I'd be all for it.

**Comment by L3MON4D3** [comment]
Maybe put both into a table and that into `luasnip`, keep them together.

**Comment by L3MON4D3** [comment]
Jup, that sounds good :+1:

**Comment by leiserfg** [comment]
Like this.

**Comment by L3MON4D3** [comment]
Nice, that looks good.
Thank you!

**Pull request merged**
