### PR TITLE
add healthcheck

### PR DESCRIPTION
**Pull request by znd4**
Hi, I wasn't sure if the way I'd installed jsregexp was working, so I've tried to implement a `:checkhealth`. Let me

I'm not sure if I've formatted the messages properly. Also, on my machine the `require("luasnip.util.jsregexp")` raises an exception instead of returning `false`, but I don't think that that's an issue unless luasnip needs more than one check in the future.

### CODE REVIEW

**Comment by znd4** [comment]
FWIW, I've tried to install `jsregexp` with [home-manager's extraLuaPackages](https://nix-community.github.io/home-manager/options.xhtml#opt-programs.neovim.extraLuaPackages), and this is what I see in the new `checkhealth` entry:

```
==============================================================================
luasnip: require("luasnip.health").check()

- ERROR Failed to run healthcheck for "luasnip" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...d4/.local/share/nvim/lazy/LuaSnip/lua/luasnip/health.lua:5: module 'luasnip.util.jsregexp' not found:
  no field package.preload['luasnip.util.jsregexp']
  cache_loader: module luasnip.util.jsregexp not found
  cache_loader_lib: module luasnip.util.jsregexp not found
  no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/luasnip/util/jsregexp.lua'
  no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/luasnip/util/jsregexp/init.lua'
  no file '/nix/store/0fixka4ad3cwvcsx52i2i5f5q7m3scwb-luajit2.1-jsregexp-0.0.6-1/share/lua/5.1/luasnip/util/jsregexp.lua'
  no file '/nix/store/0fixka4ad3cwvcsx52i2i5f5q7m3scwb-luajit2.1-jsregexp-0.0.6-1/share/lua/5.1/luasnip/util/jsregexp/init.lua'
  no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/lib/lua/5.1/luasnip/util/jsregexp.so'
  no file '/nix/store/0fixka4ad3cwvcsx52i2i5f5q7m3scwb-luajit2.1-jsregexp-0.0.6-1/lib/lua/5.1/luasnip/util/jsregexp.so'
  no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/lib/lua/5.1/luasnip.so'
  no file '/nix/store/0fixka4ad3cwvcsx52i2i5f5q7m3scwb-luajit2.1-jsregexp-0.0.6-1/lib/lua/5.1/luasnip.so'
  stack traceback:
  [C]: in function 'require'
  ...d4/.local/share/nvim/lazy/LuaSnip/lua/luasnip/health.lua:5: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

**Comment by L3MON4D3** [comment]
Hey, that's pretty cool, thank you!
(the failing tests are unrelated to these changes ;) )

**Comment by mathjiajia** [comment]
since jsregexp is optional, it is better to replace error with warning.

**Comment by L3MON4D3** [comment]
Ay, thanks for the suggestions, good points :+1:
I'll amend them :)

**Pull request merged**
